# Generated by Django 6.0.4 on 2026-06-09 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_supplier_customer_address_product_buy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='description',
        ),
    ]
