# Generated by Django 6.0.4 on 2026-06-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_description_remove_product_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quick_product',
            field=models.BooleanField(default=False),
        ),
    ]
