# Generated by Django 6.0.4 on 2026-06-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_quick_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imei',
            field=models.CharField(blank=True, help_text='Optional IMEI number', max_length=50, null=True),
        ),
    ]
